### ISSUE TITLE
Grouped nodes & other planned features？

### ISSUE THREAD

**Issue by isteelcx** [paceholder/nodeeditor#333] opened 2022-11-23 15:54 UTC
![image](https://user-images.githubusercontent.com/45957575/203591286-1d62194b-c574-4b14-be18-615517d2bf3c.jpeg)
small nodes can be include to big nodes？

**Comment by isteelcx** [comment] 2022-11-24 10:24
1. Can you talk about your vision for the NodeEditor project? What features do you think you need to add?

2. What basic functional attributes do you think a fully extensible node based editor should have?

**Comment by paceholder** [comment] 2022-11-24 10:36
I am finishing up the version 3, curently writing the documentation.

For the largest features I still want to imlemen I can name:
1. Grouping as in your pictures above
2. Experiment with the QML frontend and see how it goes.
3. Python bindings (help needed).
4. Custom painting. This is partially done. Now you can define your own `NodeGeometry` class and define positions of ports and labels. Additionally, there is an abstract class for `NodePainter` to do your own drawing. I think I need to make an example for this code and decide what is still missing.

Some minor things inspired from pull-requests for version 2:
1. [done] Undo-redo.
2. [done] Dynamic ports.
3. [done] Headless mode.
4. [done] Model-view approach, i.e. a single graph model defines the whole graph
5. [in progress] Ctrl-D for inserting a duplicate of the selected object.s

**Comment by isteelcx** [comment] 2022-11-24 12:21
There are also some personal suggestions, if you feel wrong please don't mind!

In my opinion, the programming style shown by Qt source code can increase the beauty and readability of the code. Whether it is the naming of variables or the indentation of logical paragraphs, I believe this aspect can also improve the identification of your project.On the other hand, keeping the code style consistent with the Qt source code will also help promote your project, which may one day be widely used as a popular Qt module library.I have intercepted a piece of code in the Qt source code that can express my ideas！
![图片](https://user-images.githubusercontent.com/45957575/203780588-cb0b1940-702c-404d-a5a2-845147c99d4d.png)

**Comment by paceholder** [comment] 2022-11-24 14:29
I do not have any favorite code style -- the main thing is that the formatting is consistant in all the files.
Any help with the `.clang-format` config would be greatly appreciated. When it comes to coding, I usually spend time on implementing features and never get to make a formatting config.

I personally use the [uncrustify](https://github.com/uncrustify/uncrustify) formatter, it is not that widely accepted and doesn't seem to become an industry standard any time soon.

There were "contributors" who complained about my slow development and were diccussing making a hard fork and "finally do the work propertly" -- I am still waiting for a promised clang-format file from them.

**Comment by Daguerreo** [comment] 2022-11-24 17:17
> I do not have any favorite code style -- the main thing is that the formatting stays consistent in all the files. Any help with the `.clang-format` config would be greatly appreciated. When it comes to coding, I usually spend time on implementing features and never get to making a formatting config.
> 
> I personally use the [uncrustify](https://github.com/uncrustify/uncrustify) formatter, it is not that widely accepted and doesn't seem to become an industry standard any time soon.
> 
> There were "contributors" who complained about my slow development and were diccussing making a hard fork and "finally do the work properly" -- I am still waiting for a promised clang-format file from them.

Hi pace, do you have a preferred style or a standard one can be used? If you point out a set of rules I can make a MR for that.

**Comment by Daguerreo** [comment] 2022-11-24 17:19
> I do not have any favorite code style -- the main thing is that the formatting stays consistent in all the files. Any help with the `.clang-format` config would be greatly appreciated. When it comes to coding, I usually spend time on implementing features and never get to making a formatting config.
> 
> I personally use the [uncrustify](https://github.com/uncrustify/uncrustify) formatter, it is not that widely accepted and doesn't seem to become an industry standard any time soon.
> 
> There were "contributors" who complained about my slow development and were diccussing making a hard fork and "finally do the work properly" -- I am still waiting for a promised clang-format file from them.

Hi @paceholder, do you have a preferred style or a standard one can be used? If you point out a set of rules I can make a MR for that.

**Comment by Daguerreo** [comment] 2022-11-24 17:28
Clang-format standards in Qt Creator are LLVM, Google, Chromium, Mozilla, Webkit. Using one of these could be easier because follow a standard, it's easily modifyable but you should point out the rules then, at least for spacing, columns and parenthesis.

Clang-format checks can be added in CI pipelines in and effective way. I'm not used with Github Action since I'm using Gitlab for that, so I'm not able a MR for that too but I could provide a snippet for the job or a script.

**Comment by isteelcx** [comment] 2022-11-25 00:37
when will you push your 3 version to master？

**Comment by isteelcx** [comment] 2022-11-25 02:04
> I do not have any favorite code style -- the main thing is that the formatting stays consistent in all the files. Any help with the `.clang-format` config would be greatly appreciated. When it comes to coding, I usually spend time on implementing features and never get to making a formatting config.
> 
> I personally use the [uncrustify](https://github.com/uncrustify/uncrustify) formatter, it is not that widely accepted and doesn't seem to become an industry standard any time soon.
> 
> There were "contributors" who complained about my slow development and were diccussing making a hard fork and "finally do the work properly" -- I am still waiting for a promised clang-format file from them.

https://wiki.qt.io/Qt_Coding_Style

**Comment by paceholder** [comment] 2022-11-25 15:41
@Daguerreo I think it makes sense to stick to the Qt's formatting guidelines according to @isteelcx . It would be great if you could check the available configs. After following the @isteelcx links I found two files
https://raw.githubusercontent.com/qt-creator/qt-creator/master/.clang-format
https://code.qt.io/cgit/qt/qt5.git/tree/_clang-format

@isteelcx I hope I push this weekend. Maybe earlier if I finish the docs today

**Comment by isteelcx** [comment] 2022-11-27 08:21
Thank you for your excellent work and share, I look forward to using your new push.

**Comment by isteelcx** [comment] 2022-11-28 14:08
@paceholder  Hi ,when will you push your new feature?

**Comment by paceholder** [comment] 2022-11-28 14:13
It is merged

**Closed by paceholder** 2022-11-28 14:13 UTC

**Comment by isteelcx** [comment] 2022-11-28 14:47
@paceholder  It seems that you have a new goal to become the popular Qt node library. This project without major changes for a long time has finally started a new great journey, looking forward to your great innovation!

**Comment by paceholder** [comment] 2022-11-28 16:21
@isteelcx 
![image](https://user-images.githubusercontent.com/322952/204328508-0be26521-20b8-4c5a-84dd-b1c0a0cb2611.png)
